import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LoginOne</Link>
        </li>
        <li>
          <Link to="/homeone">HomeOne</Link>
        </li>
        <li>
          <Link to="/notificaesone">NotificaesOne</Link>
        </li>
        <li>
          <Link to="/catalago">Catalago</Link>
        </li>
        <li>
          <Link to="/pedidos">Pedidos</Link>
        </li>
        <li>
          <Link to="/reembolsos">Reembolsos</Link>
        </li>
        <li>
          <Link to="/produtos">Produtos</Link>
        </li>
        <li>
          <Link to="/integraesone">IntegraesOne</Link>
        </li>
        <li>
          <Link to="/suporte">Suporte</Link>
        </li>
        <li>
          <Link to="/configuraes">Configuraes</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/notificaes">Notificaes</Link>
        </li>
        <li>
          <Link to="/produtosone">ProdutosOne</Link>
        </li>
        <li>
          <Link to="/ordens">Ordens</Link>
        </li>
        <li>
          <Link to="/envios">Envios</Link>
        </li>
        <li>
          <Link to="/finaceiro">Finaceiro</Link>
        </li>
        <li>
          <Link to="/integraes">Integraes</Link>
        </li>
        <li>
          <Link to="/suporteone">SuporteOne</Link>
        </li>
        <li>
          <Link to="/configuraesone">ConfiguraesOne</Link>
        </li>
        <li>
          <Link to="/simuladordefretes">Simuladordefretes</Link>
        </li>
        <li>
          <Link to="/novoprosuto">Novoprosuto</Link>
        </li>
        <li>
          <Link to="/selecioneoperfilone">SelecioneoperfilOne</Link>
        </li>
        <li>
          <Link to="/selecioneoperfil">Selecioneoperfil</Link>
        </li>
        <li>
          <Link to="/cadastrarseone">CadastrarseOne</Link>
        </li>
        <li>
          <Link to="/cadastrarse">Cadastrarse</Link>
        </li>
        <li>
          <Link to="/importareimportar">Importareimportar</Link>
        </li>
        <li>
          <Link to="/senhaone">SenhaOne</Link>
        </li>
        <li>
          <Link to="/senha">Senha</Link>
        </li>
        <li>
          <Link to="/seucadastrofoiconcluidocomsucessoone">
            SeucadastrofoiconcluidocomsucessoOne
          </Link>
        </li>
        <li>
          <Link to="/seucadastrofoiconcluidocomsucesso">
            Seucadastrofoiconcluidocomsucesso
          </Link>
        </li>
        <li>
          <Link to="/tutorialdaplataforma">Tutorialdaplataforma</Link>
        </li>
        <li>
          <Link to="/tutorialdaplataformaone">TutorialdaplataformaOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
